# Makefile for LaTeX documents

# TEXFILES = $(wildcard *.tex)

#TEXFILES contains usually only the header file
#The pdf file will be called header_docu.pdf, so you better give
#a suitable name for your header file
TEXFILES = tasks2015-spec.tex
PROJECTNAME = tasks2015-spec

DEPS = tasks2015-spec.tex doc-ctrl.tex sections/tasks.tex sections/intro.tex

DIRS=. sections images

include latex/Makefile

