# Makefile for LaTeX documents

# TEXFILES = $(wildcard *.tex)

#TEXFILES contains usually only the header file
#The pdf file will be called header_docu.pdf, so you better give
#a suitable name for your header file
TEXFILES = spec.tex
PROJECTNAME = spec

DEPS = spec.tex sections/intro.tex  sections/interactions.tex sections/autosub.tex

DIRS=. sections images

include latex/Makefile

