# coding: utf-8

"""
    HDL Testing Platform

    REST API for HDL TP  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Pin(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'begin': 'int',
        'end': 'int'
    }

    attribute_map = {
        'name': 'name',
        'begin': 'begin',
        'end': 'end'
    }

    def __init__(self, name=None, begin=None, end=None):  # noqa: E501
        """Pin - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._begin = None
        self._end = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if begin is not None:
            self.begin = begin
        if end is not None:
            self.end = end

    @property
    def name(self):
        """Gets the name of this Pin.  # noqa: E501

        pin  # noqa: E501

        :return: The name of this Pin.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Pin.

        pin  # noqa: E501

        :param name: The name of this Pin.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def begin(self):
        """Gets the begin of this Pin.  # noqa: E501

        begin  # noqa: E501

        :return: The begin of this Pin.  # noqa: E501
        :rtype: int
        """
        return self._begin

    @begin.setter
    def begin(self, begin):
        """Sets the begin of this Pin.

        begin  # noqa: E501

        :param begin: The begin of this Pin.  # noqa: E501
        :type: int
        """

        self._begin = begin

    @property
    def end(self):
        """Gets the end of this Pin.  # noqa: E501

        end  # noqa: E501

        :return: The end of this Pin.  # noqa: E501
        :rtype: int
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this Pin.

        end  # noqa: E501

        :param end: The end of this Pin.  # noqa: E501
        :type: int
        """

        self._end = end

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Pin, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pin):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
