#
# Makefile
# $Log: Makefile,v $
# Revision 1.1  2005/01/20 19:25:29  hofrat
# first shot for bash intro
#
#


# Makefile for LaTeX documents

# TEXFILES = $(wildcard *.tex)

#TEXFILES contains usually only the header file
#The pdf file will be called header_docu.pdf, so you better give
#a suitable name for your header file
TEXFILES = user_manual.tex
PROJECTNAME = user_manual 

DEPS = content.tex user_manual.tex doc-ctrl.tex

include latex/Makefile

