# Makefile for LaTeX documents

# TEXFILES = $(wildcard *.tex)

#TEXFILES contains usually only the header file
#The pdf file will be called header_docu.pdf, so you better give
#a suitable name for your header file
TEXFILES = tasks-spec.tex
PROJECTNAME = tasks-spec

DEPS = tasks-spec.tex doc-ctrl.tex sections/tasks.tex sections/intro.tex

DIRS=. sections images

include latex/Makefile

