# Makefile for LaTeX documents

# TEXFILES = $(wildcard *.tex)

#TEXFILES contains usually only the header file
#The pdf file will be called header_docu.pdf, so you better give
#a suitable name for your header file
TEXFILES = usermanual.tex
PROJECTNAME = usermanual

DEPS = usermanual.tex doc-ctrl.tex sections/bugs.tex sections/logerror.tex sections/manualoverview.tex sections/setup.tex sections/velsoverview.tex sections/installation.tex

DIRS=. sections images

include latex/Makefile

