# coding: utf-8

"""
    HDL Testing Platform

    REST API for HDL TP  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_a_new_user(self):
        """Test case for create_a_new_user

        Creates a new User  # noqa: E501
        """
        pass

    def test_delete_a_user(self):
        """Test case for delete_a_user

        delete a user given its identifier  # noqa: E501
        """
        pass

    def test_get_a_user(self):
        """Test case for get_a_user

        get a user given its identifier  # noqa: E501
        """
        pass

    def test_list_of_registered_users(self):
        """Test case for list_of_registered_users

        List all registered users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
